<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Raj" failures="1" tests="5" name="Default test(failed)" time="0.085" errors="0" timestamp="2023-02-16T21:23:45 IST">
  <testcase classname="TestNGInterview.RetryExample2" name="testcase1" time="0.014">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNGInterview.RetryExample2" name="testcase1" time="0.001">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNGInterview.RetryExample2" name="testcase1" time="0.001">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNGInterview.RetryExample2" name="testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNGInterview.RetryExample2" name="testcase1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNGInterview.RetryExample2.testcase1(RetryExample2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestNGInterview.RetryExample2" name="testcase2" time="0.0">
    <ignored/>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Default test(failed) -->
