<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Raj" failures="1" tests="1" name="Default test(failed)(failed)" time="0.069" errors="0" timestamp="2022-12-22T18:35:15 IST">
  <testcase classname="TestNGInterview.RerunFailedtestcase" name="equal3" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [10] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [5]
at TestNGInterview.RerunFailedtestcase.equal3(RerunFailedtestcase.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- equal3 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase" name="equal2" time="0.0">
    <ignored/>
  </testcase> <!-- equal2 -->
  <testcase classname="TestNGInterview.RerunFailedtestcase" name="equal1" time="0.0">
    <ignored/>
  </testcase> <!-- equal1 -->
</testsuite> <!-- Default test(failed)(failed) -->
